[workspace]
members = ["rcgen", "rustls-cert-gen"]
resolver = "2"

[workspace.dependencies]
aws-lc-rs = { version = "1.6.0", default-features = false }
pem = "3.0.2"
x509-parser = "0.17"

#XXX: using 'my_fork' feature ensures the current crate uses the dep from the fork and allows that fork to control any extra features like tracing.
pki-types = { package = "rustls-pki-types", version = "1.4.1", features=["my_fork"] }
ring = { version="0.17", features=["my_fork"] }

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2021"
readme = "README.md"
description = "Rust X.509 certificate generator"
repository = "https://github.com/rustls/rcgen"
keywords = ["mkcert", "ca", "certificate"]


[profile.dev]
opt-level = 0
debug = 1 #keep size down
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[patch.crates-io]
ring = { path = "/home/user/SOURCE/github/modified_forks/ring" } #patched to zeroize on drop
rustls-pki-types = { path = "/home/user/SOURCE/github/modified_forks/pki-types" } #patched with ./zeroize_on_drop.patch


